### ISSUE TITLE
Input sequence padding

### ISSUE THREAD

**Issue by WangMuT** [Sunnydreamrain/IndRNN_pytorch#6]
Hello,
Thank you verymuch for sharing your work.
I have a question about input shape
[48000, 300,50,3] input shape --> As per I understood ,300 represents sequence length of one .skeleton file . When we have .skeletion files such as 154 ,155 sequence lengths ,did you fill the rest of the length with zero padding to make it as 300 sequence length ?
Will it affects the accuracy of action recognition?

Thank you and waiting for your reply.

**Comment by Sunnydreamrain** [comment]
Hi,

Yes. The sequences are filled with zero to be 300. That is why we used another data array 'len' to indicate the real length of the data.

**Comment by Anirudh257** [comment]
@Sunnydreamrain, but in your approach, you are randomly sampling 20 frames from each sequence. If a sequence is padded with many 0's ( like the sequences having the length 154, 155 as specified in the above example), there is a chance that we pick only the 0's consisting frames during training causing a loss in training. Isn't it better to create variable length samples in the .npy files?

**Comment by Sunnydreamrain** [comment]
@Anirudh257 The "len" arrary indicates the real length of the data, thus you can sample 20 frames within the real data.

Yes. It is better to create variable length samples in the npy files if it can be loaded to the memory and does not increase reading time.

**Comment by Anirudh257** [comment]
@Sunnydreamrain, thanks for the clarification.
