### ISSUE TITLE
Word level PTB repo?

### ISSUE THREAD

**Issue by XintianHan** [Sunnydreamrain/IndRNN_pytorch#7]
I noticed that there are word-level PTB results in the paper but I only find character level in the repo. Is there any folder for the word level PTB?

**Comment by Sunnydreamrain** [comment]
Uploaded. Please check again.

**Comment by XintianHan** [comment]
Thanks! It works now. I think you may also want to update the script option "--data=data/ptb." to "--data=data/penn/" for penn.

**Comment by dmahan93** [comment]
Looks like the character level PTB got wiped out with this commit

**Comment by Sunnydreamrain** [comment]
@dmahan93 The two tasks have been merged together. Check the description.

**Comment by Sunnydreamrain** [comment]
@XintianHan The word-level and char-level are merged together.But using your command work the same by changing the input reading line.
