### ISSUE TITLE
Settings to reproduce resIndRNN results on PTB 

### ISSUE THREAD

**Issue by sytrus-in-github** [Sunnydreamrain/IndRNN_pytorch#8]
First of all, thanks a lot for this great work!

I am trying to reproduce results with resIndRNN on word level PTB data, however following the recommended settings in the paper I was only able to get around 60 perplexity (in the paper it is around 59). Would it be possible for you to share also the configuration similar to the denseIndRNN case? Thanks a lot in advance!

By the way, to have deterministic behavior, I would also add the following three lines in `train_language.py`, see [PyTorch note on reproducibility](https://pytorch.org/docs/stable/notes/randomness.html).
```python
np.random.seed(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
```  
Also, please correct me if I am wrong, but while reading your Theano implementation, it seems that the resIndRNN implemented there uses the original resnet configuration (dense then activation layer) while this version uses the new pre-activation configuration (activation then dense layer). Would this be the reason for the different results?

**Comment by sytrus-in-github** [comment]
Update: I am now able to reproduce the approx. 59 perplexity for resIndRNN. Still wondering about the different residual block configurations though ... Thanks in advance!

**Comment by Sunnydreamrain** [comment]
Hi,

Just ran the program from my end and got the result fresh out of the server (58.02, even better than reported). I have updated the result and the running command. The configuration is the same as specified as in the paper. Please check.  
After I got a decent result from the denseIndRNN, I stopped running the resIndRNN. Better results may be achieved with optimized hyperparameters.

**Comment by sytrus-in-github** [comment]
Thanks a lot for sharing this! I will try it today.

**Comment by sytrus-in-github** [comment]
I was able to obtain similar results (58.26 perplexity). Thanks!
